# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ventanaPrincipalBoceto.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaPrincipalBoceto(object):
    def setupUi(self, VentanaPrincipalBoceto):
        VentanaPrincipalBoceto.setObjectName("VentanaPrincipalBoceto")
        VentanaPrincipalBoceto.resize(633, 390)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Recursos/Imagenes/zizIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaPrincipalBoceto.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(VentanaPrincipalBoceto)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("./../../Recursos/Imagenes/ziz.png"))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("./../../Recursos/Imagenes/zizv2.png"))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.btnZizWeb = QtWidgets.QPushButton(self.centralwidget)
        self.btnZizWeb.setObjectName("btnZizWeb")
        self.gridLayout.addWidget(self.btnZizWeb, 3, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 5, 1, 1)
        self.btnPrecioCripto = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrecioCripto.setObjectName("btnPrecioCripto")
        self.gridLayout.addWidget(self.btnPrecioCripto, 4, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 4, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        self.btnReceptorPagos = QtWidgets.QPushButton(self.centralwidget)
        self.btnReceptorPagos.setObjectName("btnReceptorPagos")
        self.gridLayout.addWidget(self.btnReceptorPagos, 5, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.txtSalidaDepuracion = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSalidaDepuracion.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.txtSalidaDepuracion.setFont(font)
        self.txtSalidaDepuracion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtSalidaDepuracion.setUndoRedoEnabled(True)
        self.txtSalidaDepuracion.setObjectName("txtSalidaDepuracion")
        self.verticalLayout_3.addWidget(self.txtSalidaDepuracion)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        VentanaPrincipalBoceto.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VentanaPrincipalBoceto)
        self.statusbar.setObjectName("statusbar")
        VentanaPrincipalBoceto.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaPrincipalBoceto)
        QtCore.QMetaObject.connectSlotsByName(VentanaPrincipalBoceto)

    def retranslateUi(self, VentanaPrincipalBoceto):
        _translate = QtCore.QCoreApplication.translate
        VentanaPrincipalBoceto.setWindowTitle(_translate("VentanaPrincipalBoceto", "ziz administrador"))
        self.label_12.setText(_translate("VentanaPrincipalBoceto", "ziz Administrador"))
        self.btnZizWeb.setText(_translate("VentanaPrincipalBoceto", "iniciar"))
        self.label_9.setText(_translate("VentanaPrincipalBoceto", "ziz Web"))
        self.pushButton_3.setText(_translate("VentanaPrincipalBoceto", "Logs"))
        self.label.setText(_translate("VentanaPrincipalBoceto", "Acciones"))
        self.label_7.setText(_translate("VentanaPrincipalBoceto", "PID(S)"))
        self.label_10.setText(_translate("VentanaPrincipalBoceto", "ziz Precio Cripto"))
        self.label_3.setText(_translate("VentanaPrincipalBoceto", "80"))
        self.label_6.setText(_translate("VentanaPrincipalBoceto", "551\n"
"478"))
        self.pushButton_6.setText(_translate("VentanaPrincipalBoceto", "Logs"))
        self.btnPrecioCripto.setText(_translate("VentanaPrincipalBoceto", "iniciar"))
        self.label_11.setText(_translate("VentanaPrincipalBoceto", "ziz Recepto Pagos"))
        self.label_2.setText(_translate("VentanaPrincipalBoceto", "Puerto"))
        self.label_4.setText(_translate("VentanaPrincipalBoceto", "80"))
        self.pushButton_4.setText(_translate("VentanaPrincipalBoceto", "Logs"))
        self.btnReceptorPagos.setText(_translate("VentanaPrincipalBoceto", "iniciar"))
        self.label_8.setText(_translate("VentanaPrincipalBoceto", "Servicio"))
        self.label_5.setText(_translate("VentanaPrincipalBoceto", "80"))
        self.pushButton_7.setText(_translate("VentanaPrincipalBoceto", "Manual"))
        self.pushButton_8.setText(_translate("VentanaPrincipalBoceto", "Salida"))
        self.txtSalidaDepuracion.setHtml(_translate("VentanaPrincipalBoceto", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[web]</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaPrincipalBoceto = QtWidgets.QMainWindow()
    ui = Ui_VentanaPrincipalBoceto()
    ui.setupUi(VentanaPrincipalBoceto)
    VentanaPrincipalBoceto.show()
    sys.exit(app.exec_())
